public class test016 <E extends Exception, T extends Thread> {
	void foo(E e){}
	void foo(T t){}
    public static void main(String[] args) {
		 System.out.println("SUCCESS");
    }
}
